spring:
  datasource:
    url: jdbc:h2:mem:repayments
    driver-class-name: org.h2.Driver
    username: repayments
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 9000